version: "3.5"
services:
  postgres:
    image: postgres:12-bullseye
    container_name: postgres
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "test_db"
      #PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./public/Init Database:/docker-entrypoint-initdb.d
      - ./db_data:/var/lib/postgresql
    ports:
      - 6434:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d test_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
volumes:
  PGDATA:
   
