version: "3.9"
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "test_db"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./public:/public
      - ./public/2. Init Database:/docker-entrypoint-initdb.d
      - ./db_data:/var/lib/postgresql/data
    ports:
      - 6434:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d test_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
volumes:
  db_data:










#   pgadmin:
#     container_name: pgadmin
#     image: dpage/pgadmin4
#     environment:
#       PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
#       PGADMIN_DEFAULT_PASSWORD: "root"
#     volumes:
#       - /home/roman/Рабочий стол/learn_Node_js/app2/pgadmin:/var/lib/pgadmin
#     ports:
#       - 5050:80
# volumes:
#   test_db:
#   pgadmin: